### ISSUE TITLE
Phonegap Build plugin

### ISSUE THREAD

**Issue by RashadPark** [avivais/phonegap-parse-plugin#47]
Hi, please submit this plugin to PG. There is one but it is old, it doesn't work with iOS.
Thanks

**Comment by Tiagojdferreira** [comment]
@RashadPark did you manage to get this plugin to work with iOS? If so, could you briefly described how you did it?

**Comment by RashadPark** [comment]
It didnt work. Phonegap cant compile it ( i tried several times

**Comment by budda** [comment]
Try opening the project in XCode and building from there. Works fine for me.
I can also build directly from the cordova / ionic CLI too.

**Comment by kamikaz1k** [comment]
@budda what iOS version are you using? And are you testing on an actual device or simulator?
I don't have an actual device to test on so I am using a simulator. And I understand simulators don't support push, but I just wanted to see if it compiled...and much to my disappointment it didn't compile. Working peachy on Android though.

**Comment by budda** [comment]
@kamikaz1k ios 9 - doing both simulator and real device (iPhone 6 and various iPads)

You're right - iOS simulators wont receive push but the binary should still build and deploy fine.
So only difference is Cordova vs Phonegap build process I guess?

**Comment by kamikaz1k** [comment]
Sorry if this sounds naive but what do you meant difference between Cordova and Phonegap? Are they not identical since the rebranding?

Here is the error I am getting btw incase you have come across it before: 
"Undefined symbols for architecture i386:"

So far I have tried:
Removing the -ObjC build flag trigger as per: https://www.parse.com/questions/undefined-symbols-for-architecture-i386-error
Adding the Facebook SDK (earlier errors were invoking Facebook related functionality)
I wanted to try running the iOS 8.4 simulator but I couldn't figure out how to do it...

Here's my log dump

**Error message:**
undefined symbols for architecture i386:
"BFTaskErrorDomain", referenced from:
___63-[PFObjectBatchController deleteObjectsAsync:withSessionToken:]_block_invoke103 in Parse(PFObjectBatchController.o)
"_BFTaskMultipleExceptionsException", referenced from:
___65+[PFObject(Private) _deepSaveAsync:withCurrentUser:sessionToken:]_block_invoke216 in Parse(PFObject.o)
"_OBJC_CLASS$BFCancellationTokenSource", referenced from:
objc-class-ref in Parse(PFFile.o)
objc-class-ref in Parse(PFQuery.o)
"_OBJC_CLASS$BFExecutor", referenced from:
objc-class-ref in Parse(PFFileManager.o)
objc-class-ref in Parse(PFObject.o)
objc-class-ref in Parse(PFUser.o)
objc-class-ref in Parse(ParseManager.o)
objc-class-ref in Parse(PFAnalyticsController.o)
objc-class-ref in Parse(PFCommandCache.o)
objc-class-ref in Parse(PFFile.o)
...
"_OBJC_CLASS$BFTask", referenced from:
objc-class-ref in Parse(PFInstallation.o)
objc-class-ref in Parse(PFEventuallyPin.o)
objc-class-ref in Parse(PFFileManager.o)
objc-class-ref in Parse(PFObject.o)
objc-class-ref in Parse(PFUser.o)
objc-class-ref in Parse(ParseManager.o)
objc-class-ref in Parse(PFAnalyticsController.o)
...
"_OBJC_CLASS$_BFTaskCompletionSource", referenced from:
objc-class-ref in Parse(PFObject.o)
objc-class-ref in Parse(PFOfflineStore.o)
objc-class-ref in Parse(PFPurchaseController.o)
objc-class-ref in Parse(BFTask+Private.o)
objc-class-ref in Parse(PFAsyncTaskQueue.o)
objc-class-ref in Parse(PFEventuallyQueue.o)
objc-class-ref in Parse(PFFileController.o)
...
"_kBFMultipleErrorsError", referenced from:
___63-[PFObjectBatchController deleteObjectsAsync:withSessionToken:]_block_invoke103 in Parse(PFObjectBatchController.o)
"_sqlite3_bind_blob", referenced from:
-[PFSQLiteDatabase _bindObject:toColumn:inStatement:] in Parse(PFSQLiteDatabase.o)
"_sqlite3_bind_double", referenced from:
-[PFSQLiteDatabase _bindObject:toColumn:inStatement:] in Parse(PFSQLiteDatabase.o)
"_sqlite3_bind_int64", referenced from:
-[PFSQLiteDatabase _bindObject:toColumn:inStatement:] in Parse(PFSQLiteDatabase.o)
"_sqlite3_bind_null", referenced from:
-[PFSQLiteDatabase _bindObject:toColumn:inStatement:] in Parse(PFSQLiteDatabase.o)
"_sqlite3_bind_parameter_count", referenced from:
-[PFSQLiteDatabase _executeQueryAsync:withArgumentsInArray:cachingEnabled:] in Parse(PFSQLiteDatabase.o)
"_sqlite3_bind_text", referenced from:
___34-[PFDateFormatter dateFromString:]_block_invoke in Parse(PFDateFormatter.o)
-[PFSQLiteDatabase _bindObject:toColumn:inStatement:] in Parse(PFSQLiteDatabase.o)
"_sqlite3_clear_bindings", referenced from:
___34-[PFDateFormatter dateFromString:]_block_invoke in Parse(PFDateFormatter.o)
"_sqlite3_close", referenced from:
-[PFDateFormatter dealloc] in Parse(PFDateFormatter.o)
___30-[PFSQLiteDatabase closeAsync]_block_invoke in Parse(PFSQLiteDatabase.o)
"_sqlite3_column_blob", referenced from:
___45-[PFSQLiteDatabaseResult dataForColumnIndex:]_block_invoke_2 in Parse(PFSQLiteDatabaseResult.o)
"_sqlite3_column_bytes", referenced from:
___45-[PFSQLiteDatabaseResult dataForColumnIndex:]_block_invoke_2 in Parse(PFSQLiteDatabaseResult.o)
"_sqlite3_column_count", referenced from:
___46-[PFSQLiteDatabaseResult columnNameToIndexMap]_block_invoke in Parse(PFSQLiteDatabaseResult.o)
"_sqlite3_column_double", referenced from:
___34-[PFDateFormatter dateFromString:]_block_invoke in Parse(PFDateFormatter.o)
___47-[PFSQLiteDatabaseResult doubleForColumnIndex:]_block_invoke_2 in Parse(PFSQLiteDatabaseResult.o)
"_sqlite3_column_int", referenced from:
___44-[PFSQLiteDatabaseResult intForColumnIndex:]_block_invoke_2 in Parse(PFSQLiteDatabaseResult.o)
"_sqlite3_column_int64", referenced from:
___34-[PFDateFormatter dateFromString:]_block_invoke in Parse(PFDateFormatter.o)
___45-[PFSQLiteDatabaseResult longForColumnIndex:]_block_invoke_2 in Parse(PFSQLiteDatabaseResult.o)
"_sqlite3_column_name", referenced from:
___46-[PFSQLiteDatabaseResult columnNameToIndexMap]_block_invoke in Parse(PFSQLiteDatabaseResult.o)
"_sqlite3_column_text", referenced from:
___47-[PFSQLiteDatabaseResult stringForColumnIndex:]_block_invoke_2 in Parse(PFSQLiteDatabaseResult.o)
"_sqlite3_column_type", referenced from:
___47-[PFSQLiteDatabaseResult objectForColumnIndex:]_block_invoke_2 in Parse(PFSQLiteDatabaseResult.o)
___44-[PFSQLiteDatabaseResult columnIndexIsNull:]_block_invoke_2 in Parse(PFSQLiteDatabaseResult.o)
"_sqlite3_errmsg", referenced from:
-[PFSQLiteDatabase _errorWithErrorCode:] in Parse(PFSQLiteDatabase.o)
"_sqlite3_finalize", referenced from:
-[PFDateFormatter dealloc] in Parse(PFDateFormatter.o)
-[PFSQLiteDatabase _executeQueryAsync:withArgumentsInArray:cachingEnabled:] in Parse(PFSQLiteDatabase.o)
___26-[PFSQLiteStatement close]_block_invoke_2 in Parse(PFSQLiteStatement.o)
"_sqlite3_open", referenced from:
-[PFDateFormatter init] in Parse(PFDateFormatter.o)
___29-[PFSQLiteDatabase openAsync]_block_invoke in Parse(PFSQLiteDatabase.o)
"_sqlite3_prepare_v2", referenced from:
-[PFDateFormatter init] in Parse(PFDateFormatter.o)
-[PFSQLiteDatabase _executeQueryAsync:withArgumentsInArray:cachingEnabled:] in Parse(PFSQLiteDatabase.o)
"_sqlite3_reset", referenced from:
___34-[PFDateFormatter dateFromString:]_block_invoke in Parse(PFDateFormatter.o)
___26-[PFSQLiteStatement reset]_block_invoke_2 in Parse(PFSQLiteStatement.o)
"_sqlite3_step", referenced from:
___34-[PFDateFormatter dateFromString:]_block_invoke in Parse(PFDateFormatter.o)
___30-[PFSQLiteDatabaseResult step]_block_invoke_2 in Parse(PFSQLiteDatabaseResult.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

*\* BUILD FAILED **

The following build commands failed:
Ld build/emulator/TabApp.app/TabApp normal i386
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/Users/kamikaz1_k/workspace/TabApp/platforms/ios/cordova/build-debug.xcconfig,-project,TabApp.xcodeproj,ARCHS=i386,-target,TabApp,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/kamikaz1_k/workspace/TabApp/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/kamikaz1_k/workspace/TabApp/platforms/ios/build/sharedpch
Error: /Users/kamikaz1_k/workspace/TabApp/platforms/ios/cordova/run: Command failed with exit code 2
at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
at ChildProcess.emit (events.js:110:17)
at maybeClose (child_process.js:1015:16)
at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

**System info:**
Cordova CLI: 5.3.3
Ionic Version: 1.1.1
Ionic CLI Version: 1.7.6
Ionic App Lib Version: 0.6.2
ios-deploy version: 1.8.2
ios-sim version: 5.0.3
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.0.1 Build version 7A1001
